packages:
  - name: docker
    type: docker
    srcs:
      - "conf/**"
    argdeps:
      - imageRepoBase
    config:
      dockerfile: Dockerfile
      image:
        - ${imageRepoBase}/proxy:${version}
        - ${imageRepoBase}/proxy:${__pkg_version}
